---
sudo: required
services:
  - docker

cache:
  directories:
    - $HOME/.cache

language: C

env:
  - RELEASE=1
  - VERSION=1.9.16
  matrix:
    - OS=el DIST=6
    - OS=el DIST=7
    - OS=fedora DIST=24
    - OS=fedora DIST=25

script:
  - git submodule update --init --recursive
  - git describe --long
  - git clone https://github.com/packpack/packpack.git packpack
  - packpack/packpack

deploy:
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    branch: master
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
...
